### PR TITLE
Contrib updates

### PR DESCRIPTION
**Pull request by mcdonnelldean**

### CODE REVIEW

**Comment by mcdonnelldean** [comment]
@mcollina Not sure why we are erroring now, @feross contrib passed tests and this is just a doc update.

**Comment by feross** [comment]
Oh sorry, `standard` is temporarily depending on `eslint` master until the next version is released to npm. For some reason the npm version that is bundled with node 0.10 doesn't understand how to install http git dependencies.

**Comment by feross** [comment]
Discussed with the eslint folk on Gitter and they should be able to do a release by Friday, maybe sooner. In the meantime, sorry for breaking node 0.10 tests.

**Comment by mcdonnelldean** [comment]
@feross No Problem, @mcollina should I leave this open until the new version of eslint drops?

**Comment by mcollina** [comment]
I think we should drop 0.10 for this module. Being backward compatible is not really important here, we want to do mad science.

**Comment by mcdonnelldean** [comment]
+1 our target audience is most likely not using 0.10.x I'll commit this later

Kindest Regards,

Dean

**Comment by feross** [comment]
The issue should be fixed now, just FYI.

**Comment by mcdonnelldean** [comment]
@feross Awesome, we killed of 0.10.x support but good to know!

**Pull request merged**
